name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ffernandaeky
          outputs: dist/snake.svg

      - name: Upload animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Push to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout output || git checkout --orphan output
          git reset --hard
          git add dist/snake.svg
          git commit -m "Update Snake Animation"
          git push -f origin output
