name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari pada jam 00:00 UTC
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ffernandaeky
          outputs: dist/snake.svg

      - name: Upload animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: output
          folder: dist
